spring.application.name=sistema-mercado

# spring.datasource.url=jdbc:postgresql://localhost:5432/mercado
# spring.datasource.username=postgres
# spring.datasource.password=aluno
spring.datasource.url=jdbc:postgresql://dpg-d4ebr28gjchc73feckpg-a.oregon-postgres.render.com/mercado_hmyz
spring.datasource.username=mercado_hmyz_user
spring.datasource.password=JuyVjMLCL6Nu2cHoKXW3h7MPN8QXMSrg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/sistema-marcado/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
